CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat DECIMAL NOT NULL,
    lon DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN     NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)                NOT NULL,
    annotation         VARCHAR(2000)               NOT NULL,
    description        VARCHAR(7000)               NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_date     TIMESTAMP WITHOUT TIME ZONE,
    participant_limit  INTEGER                     NOT NULL,
    paid               BOOLEAN                     NOT NULL,
    request_moderation BOOLEAN                     NOT NULL,
    state              VARCHAR(50)                 NOT NULL,
    location_id        INTEGER REFERENCES locations (id),
    initiator_id       INTEGER REFERENCES users (id),
    category_id        INTEGER REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    id             BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       INTEGER REFERENCES events (id),
    compilation_id INTEGER REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT                      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(255)                NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     INTEGER REFERENCES events (id),
    user_id      INTEGER REFERENCES users (id)
);



