version: '3.8'
services:
  stats-server:
    build: stats/stats-server/
    image: "ewm-stats-server"
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_DATASOURCE_USER=root
      - POSTGRES_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service/
    image: "ewm-main-service"
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICES_STATSSERVICE_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
